# Runfile | https://crates.io/crates/runnables-cli

[dev-core]
alias = "dc"
description = "runs core --release"
cmd = "cargo run -p cicada_core --release"

[dev-periphery]
alias = "dp"
description = "runs periphery --release"
cmd = "cargo run -p cicada_periphery --release"

[dev-ui]
alias = "du"
path = "ui"
cmd = "yarn dev"

[build-ui]
alias = "bu"
path = "ui"
cmd = "yarn build"

[yarn-install]
description = "downloads latest javacript dependencies for client and frontend"
cmd = """
cd client/ts && yarn &&
cd ../../ui && yarn
"""

[gen-client]
alias = "gc"
description = "generates typescript types and build the ts client"
after = "yarn-install"
cmd = """
node ./client/ts/generate_types.mjs && \
cd ./client/ts && yarn build"""

