# Runfile | https://crates.io/crates/runnables-cli

[dev-core]
alias = "dc"
description = "runs core"
cmd = "CICADA_CONFIG_PATH=.dev/core.config.toml cargo run -p cicada_core"

[dev-periphery]
alias = "dp"
description = "runs periphery"
cmd = "CICADA_CONFIG_PATH=.dev/periphery.config.toml cargo run -p cicada_periphery"

[dev-periphery-container]
alias = "dpc"
description = "runs periphery in container"
path = ".dev"
cmd = "docker compose run -it --pull=always --rm --remove-orphans cperiphery"

[yarn-install]
description = "downloads latest javacript dependencies for client and frontend"
cmd = """
cd client/ts && yarn &&
cd ../../ui && yarn
"""

[gen-client]
alias = "gc"
description = "generates typescript types and build the ts client"
after = "yarn-install"
cmd = """
node ./client/ts/generate_types.mjs && \
cd ./client/ts && yarn build"""

[build-cicada]
alias = "bc"
cmd = "deno run --allow-all action/build.ts"
