import {
  HardDrive,
  User,
  File,
  FolderOpen,
  Server,
  KeyRound,
  CircleQuestionMark,
  KeySquare,
  SquareAsterisk,
  Search,
  Plus,
  Trash2,
  CirclePlus,
  CircleMinus,
  X,
  Save,
  Lock,
  ChevronsLeftRightEllipsis,
  Edit,
  History,
  FileLock,
  Info,
} from "lucide-react";

export const ICONS = {
  Access: Lock,
  User,
  Device: Server,
  OnboardingKey: KeyRound,
  Policy: ChevronsLeftRightEllipsis,
  Filesystem: HardDrive,
  Folder: FolderOpen,
  File,
  Checkpoint: History,
  EncryptionKey: KeySquare,
  Secret: SquareAsterisk,
  Interpolation: SquareAsterisk,
  Permission: FileLock,
  Search,
  Info,
  Create: Plus,
  Delete: Trash2,
  Add: CirclePlus,
  Remove: CircleMinus,
  Clear: X,
  Save,
  Edit,
  Unknown: CircleQuestionMark,
};
