/*
 Generated by typeshare 1.13.4
*/

export type U64 = number;

/** Nodes can be either folders or files. */
export enum NodeKind {
	Folder = "Folder",
	File = "File",
}

export interface NodeRecord {
	/** The unique inode number */
	ino: U64;
	/** The parent node ID */
	parent: U64;
	/** The name of the node */
	name: string;
	/**
	 * The kind of node.
	 * - Folder,
	 * - File,
	 */
	kind: NodeKind;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: string;
}

/** Response for [GetNode]. */
export type GetNodeResponse = NodeRecord;

/** Response for [ListNodes]. */
export type ListNodesResponse = NodeRecord[];

/** Get a node. Response: [NodeRecord]. */
export interface GetNode {
	ino: U64;
}

/**
 * Get the version of the Cicada Core api.
 * Response: [GetVersionResponse].
 */
export interface GetVersion {
}

/** Response for [GetVersion]. */
export interface GetVersionResponse {
	/** The version of the core api. */
	version: string;
}

/** List filesystem nodes. Response: [ListNodesResponse]. */
export interface ListNodes {
}

export type ReadRequest = 
	| { type: "GetVersion", params: GetVersion }
	| { type: "ListNodes", params: ListNodes }
	| { type: "GetNode", params: GetNode };

