/*
 Generated by typeshare 1.13.4
*/

export type DeviceId = string;

export type Iso8601Timestamp = string;

export interface DeviceRecord {
	/** The unique Device id */
	id: DeviceId;
	/** The name of the Device */
	name: string;
	/**
	 * The device public key.
	 * This is used to authenticate device requests.
	 */
	public_key: string;
	/**
	 * Whether device is enabled.
	 * Disabled devices cannot access any files.
	 */
	enabled: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteDevices]. */
export type BatchDeleteDevicesResponse = DeviceRecord[];

export type NodeId = string;

export type FilesystemId = string;

export type U64 = number;

/** Nodes can be either folders or files. */
export enum NodeKind {
	Folder = "Folder",
	File = "File",
}

/** Set the interpolation mode for files */
export enum InterpolationMode {
	/**
	 * - Example: `[[SECRET_NAME]]`
	 * - Escaped: `[[[SECRET_NAME]]]` (tripled)
	 */
	Brackets = "Brackets",
	/**
	 * - Example: `{{SECRET_NAME}}`
	 * - Escaped: `{{{SECRET_NAME}}}` (tripled)
	 */
	CurlyBrackets = "CurlyBrackets",
	/**
	 * - Example: `${SECRET_NAME}`
	 * - Escaped: `$${SECRET_NAME}`
	 * 
	 * Note. Does NOT support $SECRET_NAME
	 */
	EnvVar = "EnvVar",
	/**
	 * Inherit the mode from the filesystem. This is the default for files.
	 * 
	 * Note. This is only valid mode for files, not filesystems themselves.
	 */
	Inherit = "Inherit",
	/** Interpolation is disabled. */
	Disabled = "Disabled",
}

export type EncryptionKeyId = string;

/** Nodes over the API, with unencrypted data */
export interface NodeEntity {
	/** The unique node id */
	id: NodeId;
	/** Filesystem ID */
	filesystem: FilesystemId;
	/** The inode number */
	inode: U64;
	/** The parent inode number */
	parent: U64;
	/** The name of the node */
	name: string;
	/**
	 * The file permission integer.
	 * Usually represented as octet like 0o644.
	 * If not provided, will use defaults:
	 * - Folder: 0o755
	 * - File: 0o644
	 */
	perm?: number;
	/**
	 * The kind of node.
	 * - Folder,
	 * - File,
	 */
	kind?: NodeKind;
	/** The interpolation mode */
	interpolation: InterpolationMode;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: string;
	/**
	 * If the data could not be decrypted
	 * due to missing encryption key, give the missing ID
	 * for the user to know to initialize.
	 */
	missing_key?: EncryptionKeyId;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteNodes]. */
export type BatchDeleteNodesResponse = NodeEntity[];

export type OnboardingKeyId = string;

export interface OnboardingKeyRecord {
	/** The unique onboarding key id */
	id: OnboardingKeyId;
	/** The name of the onboarding key */
	name: string;
	/**
	 * The onboarding public key.
	 * This is used to authenticate onboarding requests.
	 */
	public_key: string;
	/**
	 * Whether onboarding key is enabled.
	 * Disabled onboarding keys cannot onboard devices.
	 */
	enabled: boolean;
	/** Expiry timestamp, or null for no expiry. */
	expires?: Iso8601Timestamp;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteOnboardingKeys]. */
export type BatchDeleteOnboardingKeysResponse = OnboardingKeyRecord[];

export type SecretId = string;

/** Secrets over the API, with unencrypted data */
export interface SecretEntity {
	/** The unique secret id */
	id: SecretId;
	/** The name of the secret */
	name: string;
	/**
	 * The master encryption key for this secret, if set.
	 * If this is not null while data is, it means
	 * the encryption key is not initialized.
	 */
	encryption_key?: EncryptionKeyId;
	/** Data associated with the secret. */
	data?: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteSecrets]. */
export type BatchDeleteSecretsResponse = SecretEntity[];

/** Response for [CreateDevice]. */
export type CreateDeviceResponse = DeviceRecord;

/** The available kinds external of encryption keys. */
export enum EncryptionKeyKind {
	/**
	 * Store the encryption key in memory.
	 * These must be initialized via API call after each Cicada Core startup.
	 */
	Memory = "Memory",
	/**
	 * UNSAFE DEVELOPMENT OPTION, DO NOT USE IN PRODUCTION.
	 * Load the key from a base64 encoded file on local disk.
	 */
	Disk = "Disk",
}

/**
 * Record fields are encrypted by storing them as [EncryptedData] type.
 * These keys are themselves encrypted using an [EncryptionKeyRecord],
 * which can point to an in-memory key or a remote KMS.
 */
export interface EncryptionKeyRecord {
	/** The unique encryption key id */
	id: EncryptionKeyId;
	/** The name of the encryption key. Must be unique. */
	name: string;
	/**
	 * The kind of encryption key.
	 * - Memory
	 * - Disk
	 */
	kind: EncryptionKeyKind;
	/**
	 * For on disk keys (unsafe),
	 * store the base64url encoded key
	 */
	key?: string;
	/** 32 random bytes base64url encoded */
	verification: string;
	/**
	 * verification bytes encrypted using the master key
	 * and verification nonce.
	 */
	verification_encrypted: string;
	/**
	 * The nonce to use to verify that 'verification_encrypted'
	 * decrypts to 'verification'.
	 */
	verification_nonce: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [CreateEncryptionKey]. */
export type CreateEncryptionKeyResponse = EncryptionKeyRecord;

export interface FilesystemRecord {
	/** The unique filesystem id */
	id: FilesystemId;
	/** The name of the filesystem. Must be unique. */
	name: string;
	/** The filesystem default encryption key. */
	encryption_key?: EncryptionKeyId;
	/** The default interpolation mode for the filesystem */
	interpolation?: InterpolationMode;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [CreateFilesystem]. */
export type CreateFilesystemResponse = FilesystemRecord;

/** Response for [CreateNode]. */
export type CreateNodeResponse = NodeEntity;

/** Response for [CreateSecret]. */
export type CreateSecretResponse = SecretEntity;

/** Response for [DeleteDevice]. */
export type DeleteDeviceResponse = DeviceRecord;

/** Response for [DeleteFilesystem]. */
export type DeleteFilesystemResponse = FilesystemRecord;

/** Response for [DeleteNode]. */
export type DeleteNodeResponse = NodeEntity[];

/** Response for [DeleteOnboardingKey]. */
export type DeleteOnboardingKeyResponse = OnboardingKeyRecord;

/** Response for [DeleteSecret]. */
export type DeleteSecretResponse = SecretEntity;

export type ExternalLoginId = string;

/** Response for [FindNode]. */
export type FindNodeResponse = NodeEntity;

/** Response for [FindSecret]. */
export type FindSecretResponse = SecretEntity;

/** Response for [GetDevice]. */
export type GetDeviceResponse = DeviceRecord;

/**
 * Record fields are encrypted by storing them as [EncryptedData] type.
 * These keys are themselves encrypted using an [EncryptionKeyRecord],
 * which can point to an in-memory key or a remote KMS.
 */
export interface EncryptionKeyEntity {
	/** The unique encryption key id */
	id: EncryptionKeyId;
	/** The name of the encryption key. Must be unique. */
	name: string;
	/**
	 * The kind of encryption key.
	 * - Memory
	 * - Disk
	 */
	kind: EncryptionKeyKind;
	/**
	 * For Memory keys:
	 * Whether the key has been initialized.
	 */
	initialized: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [GetEncryptionKey]. */
export type GetEncryptionKeyResponse = EncryptionKeyEntity;

/** Response for [GetFilesystem]. */
export type GetFilesystemResponse = FilesystemRecord;

/** Response for [GetNode]. */
export type GetNodeResponse = NodeEntity;

/** Response for [GetOnboardingKey]. */
export type GetOnboardingKeyResponse = OnboardingKeyRecord;

/** Response for [GetSecret]. */
export type GetSecretResponse = SecretEntity;

/** Represents an empty json object: `{}` */
export interface NoData {
}

/** Response for [InitializeEncryptionKey]. */
export type InitializeEncryptionKeyResponse = NoData;

export type JsonValue = any;

/** Response for [ListDevices]. */
export type ListDevicesResponse = DeviceRecord[];

/** Response for [ListEncryptionKeys]. */
export type ListEncryptionKeysResponse = EncryptionKeyEntity[];

/** Response for [ListFilesystems]. */
export type ListFilesystemsResponse = FilesystemRecord[];

export interface NodeListItem {
	/** The unique node id */
	id: NodeId;
	/** Filesystem ID */
	filesystem: FilesystemId;
	/** The inode number */
	inode: U64;
	/** The parent node ID */
	parent: U64;
	/** The name of the node */
	name: string;
	/**
	 * The file permission integer.
	 * Usually represented as octet like 0o644.
	 * If not provided, will use defaults:
	 * - Folder: 0o755
	 * - File: 0o644
	 */
	perm?: number;
	/**
	 * The kind of node.
	 * - Folder,
	 * - File,
	 */
	kind: NodeKind;
	/** The interpolation mode */
	interpolation: InterpolationMode;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [ListNodes]. */
export type ListNodesResponse = NodeListItem[];

/** Response for [ListOnboardingKeys]. */
export type ListOnboardingKeysResponse = OnboardingKeyRecord[];

export interface SecretListItem {
	/** The unique secret id */
	id: SecretId;
	/** The name of the secret */
	name: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [ListSecrets]. */
export type ListSecretsResponse = SecretListItem[];

/** Response for [RotateNodeEnvelopeKey]. */
export type RotateNodeEnvelopeKeyResponse = NodeEntity;

/** Response for [RotateSecretEnvelopeKey]. */
export type RotateSecretEnvelopeKeyResponse = SecretEntity;

/** Response for [UpdateDevice]. */
export type UpdateDeviceResponse = DeviceRecord;

/** Response for [UpdateEncryptionKey]. */
export type UpdateEncryptionKeyResponse = EncryptionKeyRecord;

/** Response for [UpdateFilesystem]. */
export type UpdateFilesystemResponse = FilesystemRecord;

/** Response for [UpdateNodeData]. */
export type UpdateNodeDataResponse = NodeEntity;

/** Response for [UpdateNodeEncryptionKey]. */
export type UpdateNodeEncryptionKeyResponse = NodeEntity;

/** Response for [UpdateNode]. */
export type UpdateNodeResponse = NodeEntity;

/** Response for [UpdateOnboardingKey]. */
export type UpdateOnboardingKeyResponse = OnboardingKeyRecord;

/** Response for [UpdateSecretData]. */
export type UpdateSecretDataResponse = SecretEntity;

/** Response for [UpdateSecretEncryptionKey]. */
export type UpdateSecretEncryptionKeyResponse = SecretEntity;

/** Response for [UpdateSecret]. */
export type UpdateSecretResponse = SecretEntity;

export type UserId = string;

/** Batch delete devices. Response: [BatchDeleteDevicesResponse]. */
export interface BatchDeleteDevices {
	/** The onboarding_key ID */
	ids: DeviceId[];
}

/**
 * Batch delete files / folders. Response: [BatchDeleteNodesResponse].
 * 
 * Note. Not compatible with 'move_children'.
 */
export interface BatchDeleteNodes {
	/** The onboarding_key ID */
	ids: NodeId[];
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Batch delete onboarding keys. Response: [BatchDeleteOnboardingKeysResponse]. */
export interface BatchDeleteOnboardingKeys {
	/** The onboarding key IDs */
	ids: OnboardingKeyId[];
}

/** Batch delete secrets. Response: [BatchDeleteSecretsResponse]. */
export interface BatchDeleteSecrets {
	/** The onboarding_key ID */
	ids: SecretId[];
}

/** Create a device. Response: [CreateDeviceResponse]. */
export interface CreateDevice {
	/** The name of the device */
	name: string;
	/** The public key of the device */
	public_key: string;
	/** Whether device is enabled. Default: true */
	enabled: boolean;
}

/** Create an encryption key. Response: [CreateEncryptionKeyResponse]. */
export interface CreateEncryptionKey {
	/** The name of the encryption key */
	name: string;
	/** The kind of encryption key */
	kind: EncryptionKeyKind;
	/**
	 * Disk mode only. If not provided in Disk mode,
	 * one will be generated.
	 */
	key?: string;
}

/** Create a filesystem. Response: [CreateFilesystemResponse]. */
export interface CreateFilesystem {
	/** The name of the filesystem */
	name: string;
	/**
	 * The default interpolation mode
	 * - `"Brackets"` (`[[SECRET]]`)
	 * - `"CurlyBrackets"` (`{{SECRET}}`)
	 * - `"EnvVar"` (`{{SECRET}}`)
	 * - `"Disabled"`
	 */
	interpolation?: InterpolationMode;
	/**
	 * Choose a specific encryption key.
	 * Otherwise uses the current global default.
	 */
	encryption_key?: EncryptionKeyId;
}

/** Create filesystem node. Response: [CreateNodeResponse]. */
export interface CreateNode {
	/** The filesystem ID */
	filesystem?: FilesystemId;
	/**
	 * parent inode number.
	 * Default: 1 (the root node).
	 */
	parent?: U64;
	/** The name of the node */
	name: string;
	/**
	 * The file permission integer.
	 * Usually represented as octet like 0o644.
	 * If not provided, will use defaults:
	 * - Folder: 0o755
	 * - File: 0o644
	 */
	perm?: number;
	/**
	 * The kind of node.
	 * - Folder
	 * - File
	 * 
	 * Default: **Folder**
	 */
	kind?: NodeKind;
	/**
	 * The interpolation mode (only for files)
	 * - `"Inherit"` (inherit from filesystem option) (default)
	 * - `"Brackets"` (`[[SECRET]]`)
	 * - `"CurlyBrackets"` (`{{SECRET}}`)
	 * - `"EnvVar"` (`{{SECRET}}`)
	 * - `"Disabled"` (Interpolation disabled for this file)
	 */
	interpolation?: InterpolationMode;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: string;
	/**
	 * Choose a specific encryption key.
	 * Otherwise uses the current filesystem default,
	 * followed by the current global default.
	 */
	encryption_key?: EncryptionKeyId;
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Create an onboarding key. Response: [CreateOnboardingKeyResponse]. */
export interface CreateOnboardingKey {
	/** The name of the onboarding_key */
	name: string;
	/**
	 * Optionally specify an existing private key, otherwise
	 * generate fresh key. This key is not stored directly,
	 * only the public key.
	 */
	private_key?: string;
	/** Whether device is enabled. Default: true */
	enabled: boolean;
	/**
	 * Expiry timestamp in unix milliseconds.
	 * Passing 0 or ommiting means no expiry.
	 */
	expires?: U64;
}

/** Response for [CreateOnboardingKey]. */
export interface CreateOnboardingKeyResponse {
	/**
	 * Pkcs8 encoded private key.
	 * If user passes pre existing private key, it will still return it.
	 */
	private_key: string;
	/** The created onboarding key record */
	created: OnboardingKeyRecord;
}

/** Create secret. Response: [CreateSecretResponse]. */
export interface CreateSecret {
	/** The name of the secret */
	name: string;
	/** An optional description for the secret */
	description?: string;
	/** The secret data to store encrypted. */
	data?: string;
	/**
	 * Choose a specific encryption key.
	 * Otherwise chooses the current global default.
	 */
	encryption_key?: EncryptionKeyId;
}

/** Delete a device. Response: [DeleteDeviceResponse]. */
export interface DeleteDevice {
	/** The device ID */
	id: DeviceId;
}

/**
 * Delete a filesystem. Response: [DeleteFilesystemResponse].
 * 
 * WARNING. This will also delete all nodes on the filesystem.
 */
export interface DeleteFilesystem {
	/** The filesystem ID */
	id: FilesystemId;
}

/**
 * Delete a filesystem node. Response: [DeleteNodeResponse].
 * 
 * WARNING: If the node is a folder and `move_children`
 * is not passed, all children nodes will be recursively deleted.
 */
export interface DeleteNode {
	/** The node id */
	id: NodeId;
	/**
	 * Move the children of this node to another parent.
	 * Otherwise, all children will be recursively deleted.
	 */
	move_children?: U64;
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Delete a onboarding_key. Response: [DeleteOnboardingKeyResponse]. */
export interface DeleteOnboardingKey {
	/** The onboarding_key ID */
	id: OnboardingKeyId;
}

/** Delete a secret. Response: [DeleteSecretResponse]. */
export interface DeleteSecret {
	/** The secret id */
	id: SecretId;
}

/**
 * Stored as nested record fields for data the requires application level encryption.
 * Implements envelope encryption, ensuring encryption master key rotation
 * doesn't require re-encrypting the data itself.
 */
export interface EncryptedData {
	encryption_key: EncryptionKeyId;
	/**
	 * The field key, encrypted with encryption key,
	 * and base64 encoded.
	 */
	key: string;
	key_nonce: string;
	/**
	 * Encrypted using the (decrypted) field key + data_nonce,
	 * and base64 encoded.
	 */
	data: string;
	/**
	 * Unencrypted, base64 encoded random nonce used to
	 * encrypt the 'data' with this [EncryptedData::key]
	 */
	data_nonce: string;
}

/** The available kinds external of user logins. */
export enum ExternalLoginKind {
	Oidc = "Oidc",
	Github = "Github",
	Google = "Google",
}

/** Stores external user logins */
export interface ExternalLoginRecord {
	/** The unique user login id */
	id: ExternalLoginId;
	/** The user which this method logs in */
	user: UserId;
	/**
	 * The type of login.
	 * - **Oidc**
	 * - **Github**
	 * - **Google**
	 */
	kind: ExternalLoginKind;
	/**
	 * The login method external id.
	 * - **Oidc**: The OIDC user subject identifier
	 * - **Github**: The Github user id
	 * - **Google**: The Google user id
	 */
	external_id: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/**
 * Find a node. Response: [NodeEntity].
 * 
 * Query using either:
 * - inode number (ino)
 * - name (parent inode number defaults to 1)
 */
export interface FindNode {
	/** Filesystem id */
	filesystem: FilesystemId;
	/** The node inode number */
	inode?: U64;
	/**
	 * The node parent inode number.
	 * Default: 1 (the root node).
	 */
	parent?: U64;
	/** file name */
	name?: string;
	/** Whether to interpolate secrets into file contents */
	interpolated?: boolean;
}

/** Find a secret by name. Response: [SecretEntity]. */
export interface FindSecret {
	/** secret name */
	name: string;
}

/** Get a device by id. Response: [DeviceRecord]. */
export interface GetDevice {
	/** The device id */
	id: DeviceId;
}

/** Get an encryption key. Response: [EncryptionKeyEntity]. */
export interface GetEncryptionKey {
	/** The encryption key id */
	id: EncryptionKeyId;
}

/** Get a specific filesystem by id or name. Response: [GetFilesystemResponse]. */
export interface GetFilesystem {
	/** Filesystem id or name */
	id: string;
}

/** Get a node. Response: [NodeEntity]. */
export interface GetNode {
	/** The node id */
	id: NodeId;
	/** Whether to interpolate secrets into file contents */
	interpolated?: boolean;
}

/** Get an onboarding key by id. Response: [OnboardingKeyRecord]. */
export interface GetOnboardingKey {
	/** The onboarding key id */
	id: OnboardingKeyId;
}

/** Get a secret. Response: [SecretEntity]. */
export interface GetSecret {
	/** The secret id */
	id: SecretId;
}

/**
 * Gets the username of a specific user.
 * Response: [GetUsernameResponse].
 */
export interface GetUsername {
	/** The id of the user */
	user_id: string;
}

/** Response for [GetUsername]. */
export interface GetUsernameResponse {
	/** The username of the user. */
	username: string;
	/** An optional icon for the user. */
	avatar?: string;
}

/**
 * Get the version of the Cicada Core API.
 * Response: [GetVersionResponse].
 */
export interface GetVersion {
}

/** Response for [GetVersion]. */
export interface GetVersionResponse {
	/** The version of the core api. */
	version: string;
}

/**
 * Initialize an uninitialized in-memory encryption key.
 * Response: [InitializeEncryptionKeyResponse].
 */
export interface InitializeEncryptionKey {
	/** The encryption key ID */
	id: EncryptionKeyId;
	/** base64url encoded master key */
	key: string;
}

/** List devices. Response: [ListDevicesResponse]. */
export interface ListDevices {
}

/** List encryption keys. Response: [ListEncryptionKeysResponse]. */
export interface ListEncryptionKeys {
}

/** List filesystems. Response: [ListFilesystemsResponse]. */
export interface ListFilesystems {
}

/** List filesystem nodes. Response: [ListNodesResponse]. */
export interface ListNodes {
	/** Filesystem id */
	filesystem?: FilesystemId;
	/** parent inode number. */
	parent?: U64;
}

/** List onboarding keys. Response: [ListOnboardingKeysResponse]. */
export interface ListOnboardingKeys {
}

/** List secrets. Response: [ListSecretsResponse]. */
export interface ListSecrets {
	/** Filesystem id */
	filesystem?: FilesystemId;
	/** parent isecret number. */
	parent?: U64;
}

/** Nodes stored on the database, with encrypted data */
export interface NodeRecord {
	/** The unique node id */
	id: NodeId;
	/** Filesystem ID */
	filesystem: FilesystemId;
	/** The inode number */
	inode: U64;
	/** The parent inode number */
	parent: U64;
	/** The name of the node */
	name: string;
	/**
	 * The file permission integer.
	 * Usually represented as octet like 0o644.
	 * If not provided, will use defaults:
	 * - Folder: 0o755
	 * - File: 0o644
	 */
	perm?: number;
	/**
	 * The kind of node.
	 * - Folder,
	 * - File,
	 */
	kind?: NodeKind;
	/** The interpolation mode */
	interpolation: InterpolationMode;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: EncryptedData;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Rotate a filesystem node's envelope encryption key. Response: [RotateNodeEnvelopeKeyResponse]. */
export interface RotateNodeEnvelopeKey {
	/** The node id */
	id: NodeId;
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Rotate a secret's envelope encryption key. Response: [RotateSecretEnvelopeKeyResponse]. */
export interface RotateSecretEnvelopeKey {
	/** The secret id */
	id: SecretId;
}

/** Secrets stored on the database, with encrypted data */
export interface SecretRecord {
	/** The unique secret id. */
	id: SecretId;
	/** The name of the secret. */
	name: string;
	/** Optional description for the secret. */
	description?: string;
	/** Data associated with the secret. */
	data?: EncryptedData;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/**
 * Uninitialize an in-memory encryption key after it has been initialized.
 * Response: [UninitializeEncryptionKeyResponse].
 */
export interface UninitializeEncryptionKey {
	/** The encryption key ID */
	id: EncryptionKeyId;
}

/** Response for [UninitializeEncryptionKey]. */
export interface UninitializeEncryptionKeyResponse {
	/**
	 * Whether an initialized encryption key was removed.
	 * It may be `false` because:
	 * - The encryption key was not initialized.
	 * - There is no encryption key at id.
	 */
	removed: boolean;
}

/** Update a device. Response: [UpdateDeviceResponse]. */
export interface UpdateDevice {
	/** The device ID */
	id: DeviceId;
	/** The name of the device */
	name?: string;
	/** The public key of the device */
	public_key?: string;
	/** Whether the device is enabled / has access. */
	enabled?: boolean;
}

/** Update an encryption key. Response: [UpdateEncryptionKeyResponse]. */
export interface UpdateEncryptionKey {
	/** The encryption key ID */
	id: EncryptionKeyId;
	/** The name of the encryption key */
	name?: string;
}

/** Update a filesystem. Response: [UpdateFilesystemResponse]. */
export interface UpdateFilesystem {
	/** The filesystem ID */
	id: FilesystemId;
	/** The name of the filesystem */
	name?: string;
	/**
	 * The default interpolation mode
	 * - `"Brackets"` (`[[SECRET]]`)
	 * - `"CurlyBrackets"` (`{{SECRET}}`)
	 * - `"EnvVar"` (`{{SECRET}}`)
	 * - `"Disabled"`
	 */
	interpolation?: InterpolationMode;
	/**
	 * Update default encryption key for filesystem.
	 * Note. This does not affect already created nodes.
	 */
	encryption_key?: EncryptionKeyId;
}

/** Update a filesystem node. Response: [UpdateNodeResponse]. */
export interface UpdateNode {
	/** The node id */
	id: NodeId;
	/** parent inode number. */
	parent?: U64;
	/** The name of the node */
	name?: string;
	/**
	 * The file permission integer.
	 * Usually represented as octet like 0o644.
	 * If not provided, will use defaults:
	 * - Folder: 0o755
	 * - File: 0o644
	 */
	perm?: number;
	/**
	 * The interpolation mode (only for files)
	 * - `"Inherit"` (inherit from filesystem option) (default)
	 * - `"Brackets"` (`[[SECRET]]`)
	 * - `"CurlyBrackets"` (`{{SECRET}}`)
	 * - `"EnvVar"` (`{{SECRET}}`)
	 * - `"Disabled"` (Interpolation disabled for this file)
	 */
	interpolation?: InterpolationMode;
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Update a filesystem node's encrypted data. Response: [UpdateNodeDataResponse]. */
export interface UpdateNodeData {
	/** The node id */
	id: NodeId;
	/** The node data */
	data: string;
	/** Optionally update the encryption key used as master in the envelope encryption. */
	encryption_key?: EncryptionKeyId;
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Update a filesystem node's encryption key. Response: [UpdateNodeEncryptionKeyResponse]. */
export interface UpdateNodeEncryptionKey {
	/** The node id */
	id: NodeId;
	/** Update the encryption key used as master in the envelope encryption. */
	encryption_key: EncryptionKeyId;
	/** Whether to interpolate secrets into returned file contents */
	interpolated?: boolean;
}

/** Update an onboarding key. Response: [UpdateOnboardingKeyResponse]. */
export interface UpdateOnboardingKey {
	/** The onboarding_key ID */
	id: OnboardingKeyId;
	/** The name of the onboarding key */
	name?: string;
	/** The onboarding key public key */
	public_key?: string;
	/** Whether the onboarding key is enabled / can onboard. */
	enabled?: boolean;
}

/** Update a secret. Response: [UpdateSecretResponse]. */
export interface UpdateSecret {
	/** The secret id */
	id: SecretId;
	/** The name of the secret */
	name?: string;
	/** A description for the secret */
	description?: string;
}

/** Update a secret's encrypted data. Response: [UpdateSecretDataResponse]. */
export interface UpdateSecretData {
	/** The secret id */
	id: SecretId;
	/** The secret data */
	data: string;
	/** Optionally update the encryption key used as master in the envelope encryption. */
	encryption_key?: EncryptionKeyId;
}

/** Update a secret's encryption key. Response: [UpdateSecretEncryptionKeyResponse]. */
export interface UpdateSecretEncryptionKey {
	/** The secret id */
	id: SecretId;
	/** Update the encryption key used as master in the envelope encryption. */
	encryption_key: EncryptionKeyId;
}

/** Users queryable from the API */
export interface UserEntity {
	/** The unique user id */
	id: UserId;
	/** The name of the user, ie username */
	username: string;
	/** Link for user avatar, or empty string. */
	avatar: string;
	/**
	 * Whether user is enabled.
	 * Disabled users cannot log in and have no API access.
	 */
	enabled: boolean;
	/** Whether user has password set. */
	password: boolean;
	/** The external login methods the user has set. */
	external_logins: ExternalLoginRecord[];
	/** Whether user is enrolled in passkey 2fa */
	passkey: boolean;
	/** Whether user is enrolled in TOTP 2fa */
	totp: boolean;
	/** Allow external logins to skip 2fa. */
	external_skip_2fa: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Users on the database */
export interface UserRecord {
	/** The unique user id */
	id: UserId;
	/** The name of the user, ie username */
	username: string;
	/** Link for user avatar, or empty string. */
	avatar: string;
	/**
	 * Whether user is enabled.
	 * Disabled users cannot log in and have no API access.
	 */
	enabled: boolean;
	/**
	 * Hashed user password.
	 * Empty if local login is not set.
	 */
	password: string;
	/** User passkey config for 2fa */
	passkey?: JsonValue;
	/**
	 * User totp secret.
	 * TODO: encryption
	 */
	totp_secret: string;
	/** Allow external logins to skip 2fa. */
	external_skip_2fa: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/**
 * The types of clients which can
 * authenticate with the Cicada API.
 */
export enum ClientType {
	User = "User",
	Device = "Device",
	OnboardingKey = "OnboardingKey",
}

export type ReadRequest = 
	| { type: "GetVersion", params: GetVersion }
	| { type: "GetUsername", params: GetUsername }
	| { type: "ListDevices", params: ListDevices }
	| { type: "GetDevice", params: GetDevice }
	| { type: "ListOnboardingKeys", params: ListOnboardingKeys }
	| { type: "GetOnboardingKey", params: GetOnboardingKey }
	| { type: "ListFilesystems", params: ListFilesystems }
	| { type: "GetFilesystem", params: GetFilesystem }
	| { type: "ListNodes", params: ListNodes }
	| { type: "GetNode", params: GetNode }
	| { type: "FindNode", params: FindNode }
	| { type: "ListSecrets", params: ListSecrets }
	| { type: "GetSecret", params: GetSecret }
	| { type: "FindSecret", params: FindSecret }
	| { type: "ListEncryptionKeys", params: ListEncryptionKeys }
	| { type: "GetEncryptionKey", params: GetEncryptionKey };

export enum Timelength {
	/** `1-sec` */
	OneSecond = "1-sec",
	/** `1-sec` */
	TwoSeconds = "2-sec",
	/** `1-sec` */
	ThreeSeconds = "3-sec",
	/** `5-sec` */
	FiveSeconds = "5-sec",
	/** `10-sec` */
	TenSeconds = "10-sec",
	/** `15-sec` */
	FifteenSeconds = "15-sec",
	/** `30-sec` */
	ThirtySeconds = "30-sec",
	/** `1-min` */
	OneMinute = "1-min",
	/** `2-min` */
	TwoMinutes = "2-min",
	/** `3-min` */
	ThreeMinutes = "3-min",
	/** `5-min` */
	FiveMinutes = "5-min",
	/** `10-min` */
	TenMinutes = "10-min",
	/** `15-min` */
	FifteenMinutes = "15-min",
	/** `30-min` */
	ThirtyMinutes = "30-min",
	/** `1-hr` */
	OneHour = "1-hr",
	/** `2-hr` */
	TwoHours = "2-hr",
	/** `3-hr` */
	ThreeHours = "3-hr",
	/** `6-hr` */
	SixHours = "6-hr",
	/** `8-hr` */
	EightHours = "8-hr",
	/** `12-hr` */
	TwelveHours = "12-hr",
	/** `1-day` */
	OneDay = "1-day",
	/** `2-day` */
	TwoDays = "2-day",
	/** `3-day` */
	ThreeDays = "3-day",
	/** `1-wk` */
	OneWeek = "1-wk",
	/** `2-wk` */
	TwoWeeks = "2-wk",
	/** `30-day` */
	ThirtyDays = "30-day",
}

export type WriteRequest = 
	| { type: "CreateDevice", params: CreateDevice }
	| { type: "UpdateDevice", params: UpdateDevice }
	| { type: "DeleteDevice", params: DeleteDevice }
	| { type: "BatchDeleteDevices", params: BatchDeleteDevices }
	| { type: "CreateOnboardingKey", params: CreateOnboardingKey }
	| { type: "UpdateOnboardingKey", params: UpdateOnboardingKey }
	| { type: "DeleteOnboardingKey", params: DeleteOnboardingKey }
	| { type: "BatchDeleteOnboardingKeys", params: BatchDeleteOnboardingKeys }
	| { type: "CreateFilesystem", params: CreateFilesystem }
	| { type: "UpdateFilesystem", params: UpdateFilesystem }
	| { type: "DeleteFilesystem", params: DeleteFilesystem }
	| { type: "CreateNode", params: CreateNode }
	| { type: "UpdateNode", params: UpdateNode }
	| { type: "UpdateNodeData", params: UpdateNodeData }
	| { type: "UpdateNodeEncryptionKey", params: UpdateNodeEncryptionKey }
	| { type: "RotateNodeEnvelopeKey", params: RotateNodeEnvelopeKey }
	| { type: "DeleteNode", params: DeleteNode }
	| { type: "BatchDeleteNodes", params: BatchDeleteNodes }
	| { type: "CreateSecret", params: CreateSecret }
	| { type: "UpdateSecret", params: UpdateSecret }
	| { type: "UpdateSecretData", params: UpdateSecretData }
	| { type: "UpdateSecretEncryptionKey", params: UpdateSecretEncryptionKey }
	| { type: "RotateSecretEnvelopeKey", params: RotateSecretEnvelopeKey }
	| { type: "DeleteSecret", params: DeleteSecret }
	| { type: "BatchDeleteSecrets", params: BatchDeleteSecrets }
	| { type: "CreateEncryptionKey", params: CreateEncryptionKey }
	| { type: "UpdateEncryptionKey", params: UpdateEncryptionKey }
	| { type: "InitializeEncryptionKey", params: InitializeEncryptionKey }
	| { type: "UninitializeEncryptionKey", params: UninitializeEncryptionKey };

