/*
 Generated by typeshare 1.13.4
*/

export type DeviceId = string;

export type Iso8601Timestamp = string;

export interface DeviceRecord {
	/** The unique Device id */
	id: DeviceId;
	/** The name of the Device */
	name: string;
	/**
	 * The device public key.
	 * This is used to authenticate device requests.
	 */
	public_key: string;
	/**
	 * Whether device is enabled.
	 * Disabled devices cannot access any files.
	 */
	enabled: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteDevices]. */
export type BatchDeleteDevicesResponse = DeviceRecord[];

export type NodeId = string;

export type FilesystemId = string;

export type U64 = number;

/** Nodes can be either folders or files. */
export enum NodeKind {
	Folder = "Folder",
	File = "File",
}

export interface NodeRecord {
	/** The unique node id */
	id: NodeId;
	/** Filesystem ID */
	filesystem: FilesystemId;
	/** The inode number */
	inode: U64;
	/** The parent inode number */
	parent: U64;
	/** The name of the node */
	name: string;
	/**
	 * The kind of node.
	 * - Folder,
	 * - File,
	 */
	kind?: NodeKind;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteNodes]. */
export type BatchDeleteNodesResponse = NodeRecord[];

export type OnboardingKeyId = string;

export interface OnboardingKeyRecord {
	/** The unique onboarding key id */
	id: OnboardingKeyId;
	/** The name of the onboarding key */
	name: string;
	/**
	 * The onboarding public key.
	 * This is used to authenticate onboarding requests.
	 */
	public_key: string;
	/**
	 * Whether onboarding key is enabled.
	 * Disabled onboarding keys cannot onboard devices.
	 */
	enabled: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [BatchDeleteOnboardingKeys]. */
export type BatchDeleteOnboardingKeysResponse = OnboardingKeyRecord[];

/** Response for [CreateDevice]. */
export type CreateDeviceResponse = DeviceRecord;

export interface FilesystemRecord {
	/** The unique filesystem id */
	id: FilesystemId;
	/** The name of the filesystem. Must be unique. */
	name: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [CreateFilesystem]. */
export type CreateFilesystemResponse = FilesystemRecord;

/** Response for [CreateNode]. */
export type CreateNodeResponse = NodeRecord;

/** Response for [DeleteDevice]. */
export type DeleteDeviceResponse = DeviceRecord;

/** Response for [DeleteFilesystem]. */
export type DeleteFilesystemResponse = FilesystemRecord;

/** Response for [DeleteNode]. */
export type DeleteNodeResponse = NodeRecord[];

/** Response for [DeleteOnboardingKey]. */
export type DeleteOnboardingKeyResponse = OnboardingKeyRecord;

export type EncryptionKeyId = string;

export type ExternalLoginId = string;

/** Response for [FindNode]. */
export type FindNodeResponse = NodeRecord;

/** Response for [GetDevice]. */
export type GetDeviceResponse = DeviceRecord;

/** Response for [GetNode]. */
export type GetNodeResponse = NodeRecord;

/** Response for [GetOnboardingKey]. */
export type GetOnboardingKeyResponse = OnboardingKeyRecord;

export type UserId = string;

/** The available kinds external of user logins. */
export enum ExternalLoginKind {
	Oidc = "Oidc",
	Github = "Github",
	Google = "Google",
}

/** Stores external user logins */
export interface ExternalLoginRecord {
	/** The unique user login id */
	id: ExternalLoginId;
	/** The user which this method logs in */
	user: UserId;
	/**
	 * The type of login.
	 * - **Oidc**
	 * - **Github**
	 * - **Google**
	 */
	kind: ExternalLoginKind;
	/**
	 * The login method external id.
	 * - **Oidc**: The OIDC user subject identifier
	 * - **Github**: The Github user id
	 * - **Google**: The Google user id
	 */
	external_id: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Users queryable from the API */
export interface UserEntity {
	/** The unique user id */
	id: UserId;
	/** The name of the user, ie username */
	username: string;
	/**
	 * Whether user is enabled.
	 * Disabled users cannot log in and have no API access.
	 */
	enabled: boolean;
	/** Whether user has password set. */
	password: boolean;
	/** The external login methods the user has set. */
	external_logins: ExternalLoginRecord[];
	/** Whether user is enrolled in passkey 2fa */
	passkey: boolean;
	/** Whether user is enrolled in TOTP 2fa */
	totp: boolean;
	/** Allow external logins to skip 2fa. */
	external_skip_2fa: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

export type GetUserResponse = UserEntity;

export type JsonValue = any;

/** Response for [ListDevices]. */
export type ListDevicesResponse = DeviceRecord[];

/** Response for [ListFilesystems]. */
export type ListFilesystemsResponse = FilesystemRecord[];

export interface NodeListItem {
	/** The unique node id */
	id: NodeId;
	/** Filesystem ID */
	filesystem: FilesystemId;
	/** The inode number */
	inode: U64;
	/** The parent node ID */
	parent: U64;
	/** The name of the node */
	name: string;
	/**
	 * The kind of node.
	 * - Folder,
	 * - File,
	 */
	kind: NodeKind;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Response for [ListNodes]. */
export type ListNodesResponse = NodeListItem[];

/** Response for [ListOnboardingKeys]. */
export type ListOnboardingKeysResponse = OnboardingKeyRecord[];

export type MasterKeyId = string;

/** Response for [UpdateDevice]. */
export type UpdateDeviceResponse = DeviceRecord;

/** Response for [UpdateFilesystem]. */
export type UpdateFilesystemResponse = FilesystemRecord;

/** Response for [UpdateNode]. */
export type UpdateNodeResponse = NodeRecord;

/** Response for [UpdateOnboardingKey]. */
export type UpdateOnboardingKeyResponse = OnboardingKeyRecord;

/** Batch delete devices. Response: [BatchDeleteDevicesResponse]. */
export interface BatchDeleteDevices {
	/** The onboarding_key ID */
	ids: DeviceId[];
}

/**
 * Batch delete files / folders. Response: [BatchDeleteNodesResponse].
 * 
 * Note. Not compatible with 'move_children'.
 */
export interface BatchDeleteNodes {
	/** The onboarding_key ID */
	ids: NodeId[];
}

/** Batch delete onboarding keys. Response: [BatchDeleteOnboardingKeysResponse]. */
export interface BatchDeleteOnboardingKeys {
	/** The onboarding key IDs */
	ids: OnboardingKeyId[];
}

/** Create a device. Response: [CreateDeviceResponse]. */
export interface CreateDevice {
	/** The name of the device */
	name: string;
	/** The public key of the device */
	public_key: string;
	/** Whether device is enabled. Default: true */
	enabled: boolean;
}

/** Create a filesystem. Response: [CreateFilesystemResponse]. */
export interface CreateFilesystem {
	/** The name of the filesystem */
	name: string;
}

/** Create filesystem node. Response: [CreateNodeResponse]. */
export interface CreateNode {
	/** The filesystem ID */
	filesystem?: FilesystemId;
	/**
	 * parent inode number.
	 * Default: 1 (the root node).
	 */
	parent?: U64;
	/** The name of the node */
	name: string;
	/**
	 * The kind of node.
	 * - Folder
	 * - File
	 * 
	 * Default: **Folder**
	 */
	kind?: NodeKind;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: string;
}

/** Create an onboarding key. Response: [CreateOnboardingKeyResponse]. */
export interface CreateOnboardingKey {
	/** The name of the onboarding_key */
	name: string;
	/**
	 * Optionally provide a pre-existing Spki encoded public key
	 * generated using another method. Otherwise a new keypair will be
	 * generated and the private key returned. The private key will not be
	 * stored otherwise.
	 */
	public_key?: string;
	/** Whether device is enabled. Default: true */
	enabled: boolean;
}

/** Response for [CreateOnboardingKey]. */
export interface CreateOnboardingKeyResponse {
	/**
	 * Pkcs8 encoded private key.
	 * Only present if user *does not* pass pre existing public key to [CreateOnboardingKey].
	 */
	private_key?: string;
	/** The created onboarding key record */
	created: OnboardingKeyRecord;
}

/** Delete a device. Response: [DeleteDeviceResponse]. */
export interface DeleteDevice {
	/** The device ID */
	id: DeviceId;
}

/**
 * Delete a filesystem. Response: [DeleteFilesystemResponse].
 * 
 * WARNING. This will also delete all nodes on the filesystem.
 */
export interface DeleteFilesystem {
	/** The filesystem ID */
	id: FilesystemId;
}

/**
 * Delete a filesystem node. Response: [DeleteNodeResponse].
 * 
 * WARNING: If the node is a folder and `move_children`
 * is not passed, all children nodes will be recursively deleted.
 */
export interface DeleteNode {
	/** The node id */
	id: NodeId;
	/**
	 * Move the children of this node to another parent.
	 * Otherwise, all children will be recursively deleted.
	 */
	move_children?: U64;
}

/** Delete a onboarding_key. Response: [DeleteOnboardingKeyResponse]. */
export interface DeleteOnboardingKey {
	/** The onboarding_key ID */
	id: OnboardingKeyId;
}

export type CicadaRecordId = 
	| { table: "User", key: UserId }
	| { table: "ExternalLogin", key: ExternalLoginId }
	| { table: "Device", key: DeviceId }
	| { table: "OnboardingKey", key: OnboardingKeyId }
	| { table: "Filesystem", key: FilesystemId }
	| { table: "Node", key: NodeId }
	| { table: "EncryptionKey", key: EncryptionKeyId }
	| { table: "MasterKey", key: MasterKeyId };

/**
 * Record fields are encrypted using encryption keys stored
 * in [EncryptionKeyRecord]. These keys are themselves encrypted using
 * a master key.
 * 
 * This pattern allows both record keys and master keys to be rotated.
 */
export interface EncryptionKeyRecord {
	/** The unique encryption key id */
	id: EncryptionKeyId;
	/** The record which this key encrypts. */
	record: CicadaRecordId;
	/** Master key used to encrypt this key. */
	master: MasterKeyId;
	/** Encrypted with master key, base64 encoded. */
	key: string;
	/**
	 * Key encryption nonce, base64 encoded, or empty string.
	 * 
	 * If non-empty, is the nonce used to encrypt this key using
	 * the master key.
	 */
	nonce: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/**
 * Find a node. Response: [NodeRecord].
 * 
 * Query using either:
 * - inode number (ino)
 * - name (parent inode number defaults to 1)
 */
export interface FindNode {
	/** Filesystem id */
	filesystem: FilesystemId;
	/** The node inode number */
	inode?: U64;
	/**
	 * The node parent inode number.
	 * Default: 1 (the root node).
	 */
	parent?: U64;
	/** file name */
	name?: string;
}

/** Get a device. Response: [DeviceRecord]. */
export interface GetDevice {
	/** The device id */
	id: DeviceId;
}

/** Get a node. Response: [NodeRecord]. */
export interface GetNode {
	/** The node id */
	id: NodeId;
}

/** Get an onboarding key. Response: [OnboardingKeyRecord]. */
export interface GetOnboardingKey {
	/** The onboarding key id */
	id: OnboardingKeyId;
}

/**
 * Get calling user extracted from the request authorization.
 * Response: [UserEntity].
 */
export interface GetUser {
}

/**
 * Gets the username of a specific user.
 * Response: [GetUsernameResponse].
 */
export interface GetUsername {
	/** The id of the user */
	user_id: string;
}

/** Response for [GetUsername]. */
export interface GetUsernameResponse {
	/** The username of the user. */
	username: string;
	/** An optional icon for the user. */
	avatar?: string;
}

/**
 * Get the version of the Cicada Core api.
 * Response: [GetVersionResponse].
 */
export interface GetVersion {
}

/** Response for [GetVersion]. */
export interface GetVersionResponse {
	/** The version of the core api. */
	version: string;
}

/** List devices. Response: [ListDevicesResponse]. */
export interface ListDevices {
}

/** List filesystems. Response: [ListFilesystemsResponse]. */
export interface ListFilesystems {
}

/** List filesystem nodes. Response: [ListNodesResponse]. */
export interface ListNodes {
	/** Filesystem id */
	filesystem?: FilesystemId;
	/** parent inode number. */
	parent?: U64;
}

/** List onboarding keys. Response: [ListOnboardingKeysResponse]. */
export interface ListOnboardingKeys {
}

/**
 * Record fields are encrypted using encryption keys stored
 * in EncryptedKeyRecord. These keys themselves must be encrypted using
 * a master key.
 * 
 * Production master keys can be in memory (initialized via API call on startup),
 * or point to a remote KMS.
 * 
 * This pattern allows both record keys and master keys to be rotated.
 */
export interface MasterKeyRecord {
	/** The unique master key id */
	id: MasterKeyId;
	/** The name of the master key. Must be unique. */
	name: string;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

/** Represents an empty json object: `{}` */
export interface NoData {
}

/** Update a device. Response: [UpdateDeviceResponse]. */
export interface UpdateDevice {
	/** The device ID */
	id: DeviceId;
	/** The name of the device */
	name?: string;
	/** The public key of the device */
	public_key?: string;
	/** Whether the device is enabled / has access. */
	enabled?: boolean;
}

/** Update a filesystem. Response: [UpdateFilesystemResponse]. */
export interface UpdateFilesystem {
	/** The filesystem ID */
	id: FilesystemId;
	/** The name of the filesystem */
	name?: string;
}

/** Update a filesystem node. Response: [UpdateNodeResponse]. */
export interface UpdateNode {
	/** The node id */
	id: NodeId;
	/** parent inode number. */
	parent?: U64;
	/** The name of the node */
	name?: string;
	/**
	 * Data associated with the node.
	 * For files, this contains the file contents.
	 */
	data?: string;
}

/** Update an onboarding key. Response: [UpdateOnboardingKeyResponse]. */
export interface UpdateOnboardingKey {
	/** The onboarding_key ID */
	id: OnboardingKeyId;
	/** The name of the onboarding key */
	name?: string;
	/** The onboarding key public key */
	public_key?: string;
	/** Whether the onboarding key is enabled / can onboard. */
	enabled?: boolean;
}

/** Users on the database */
export interface UserRecord {
	/** The unique user id */
	id: UserId;
	/** The name of the user, ie username */
	username: string;
	/**
	 * Whether user is enabled.
	 * Disabled users cannot log in and have no API access.
	 */
	enabled: boolean;
	/**
	 * Hashed user password.
	 * Empty if local login is not set.
	 */
	password: string;
	/** User passkey config for 2fa */
	passkey?: JsonValue;
	/**
	 * User totp secret.
	 * TODO: encryption
	 */
	totp_secret: string;
	/** Allow external logins to skip 2fa. */
	external_skip_2fa: boolean;
	/** Created at as ISO8601 timestamp. */
	created_at: Iso8601Timestamp;
	/** Updated at as ISO8601 timestamp. */
	updated_at: Iso8601Timestamp;
}

export enum ClientType {
	User = "User",
	Device = "Device",
	OnboardingKey = "OnboardingKey",
}

export type ReadRequest = 
	| { type: "GetVersion", params: GetVersion }
	| { type: "GetUser", params: GetUser }
	| { type: "GetUsername", params: GetUsername }
	| { type: "ListDevices", params: ListDevices }
	| { type: "GetDevice", params: GetDevice }
	| { type: "ListOnboardingKeys", params: ListOnboardingKeys }
	| { type: "GetOnboardingKey", params: GetOnboardingKey }
	| { type: "ListFilesystems", params: ListFilesystems }
	| { type: "ListNodes", params: ListNodes }
	| { type: "GetNode", params: GetNode }
	| { type: "FindNode", params: FindNode };

export enum Timelength {
	/** `1-sec` */
	OneSecond = "1-sec",
	/** `1-sec` */
	TwoSeconds = "2-sec",
	/** `1-sec` */
	ThreeSeconds = "3-sec",
	/** `5-sec` */
	FiveSeconds = "5-sec",
	/** `10-sec` */
	TenSeconds = "10-sec",
	/** `15-sec` */
	FifteenSeconds = "15-sec",
	/** `30-sec` */
	ThirtySeconds = "30-sec",
	/** `1-min` */
	OneMinute = "1-min",
	/** `2-min` */
	TwoMinutes = "2-min",
	/** `3-min` */
	ThreeMinutes = "3-min",
	/** `5-min` */
	FiveMinutes = "5-min",
	/** `10-min` */
	TenMinutes = "10-min",
	/** `15-min` */
	FifteenMinutes = "15-min",
	/** `30-min` */
	ThirtyMinutes = "30-min",
	/** `1-hr` */
	OneHour = "1-hr",
	/** `2-hr` */
	TwoHours = "2-hr",
	/** `3-hr` */
	ThreeHours = "3-hr",
	/** `6-hr` */
	SixHours = "6-hr",
	/** `8-hr` */
	EightHours = "8-hr",
	/** `12-hr` */
	TwelveHours = "12-hr",
	/** `1-day` */
	OneDay = "1-day",
	/** `2-day` */
	TwoDays = "2-day",
	/** `3-day` */
	ThreeDays = "3-day",
	/** `1-wk` */
	OneWeek = "1-wk",
	/** `2-wk` */
	TwoWeeks = "2-wk",
	/** `30-day` */
	ThirtyDays = "30-day",
}

export type WriteRequest = 
	| { type: "CreateDevice", params: CreateDevice }
	| { type: "UpdateDevice", params: UpdateDevice }
	| { type: "DeleteDevice", params: DeleteDevice }
	| { type: "BatchDeleteDevices", params: BatchDeleteDevices }
	| { type: "CreateOnboardingKey", params: CreateOnboardingKey }
	| { type: "UpdateOnboardingKey", params: UpdateOnboardingKey }
	| { type: "DeleteOnboardingKey", params: DeleteOnboardingKey }
	| { type: "BatchDeleteOnboardingKeys", params: BatchDeleteOnboardingKeys }
	| { type: "CreateFilesystem", params: CreateFilesystem }
	| { type: "UpdateFilesystem", params: UpdateFilesystem }
	| { type: "DeleteFilesystem", params: DeleteFilesystem }
	| { type: "CreateNode", params: CreateNode }
	| { type: "UpdateNode", params: UpdateNode }
	| { type: "DeleteNode", params: DeleteNode }
	| { type: "BatchDeleteNodes", params: BatchDeleteNodes };

